Модуляция
htmlacademy-javascript/512667-kekstagram-25 pull request #4
Opened 2022-03-02 08:12 UTC by radamid

---
:mortar_board: [Модуляция](https://up.htmlacademy.ru/javascript/25/user/512667/tasks/9)

2022-03-02 15:33 UTC, bbalkonsky requested changes

2022-03-02 15:33 UTC, bbalkonsky commented on js/util.js
> +  return function () {
[Д5.](https://up.htmlacademy.ru/javascript/25/criteries#d5) Все функции объявлены единообразно.

2022-03-02 15:33 UTC, bbalkonsky commented on js/data.js
> +const MESSAGES = [
_нет такого критерия, можете не исправлять:_
это не сообщения, а комментарии

2022-03-02 17:33 UTC, radamid commented on js/data.js
> +const MESSAGES = [
В прошедшем задании "_Больше функций_" прописывалась структура объекта с определёнными ключами id, url, description, likes, **comments**, при чём сам _comments_ в свою очередь является массивом объектов с ключами id, avatar, **message**, name, цитирую: "для формирования текста комментария — _message_ — вам необходимо взять одно или два случайных предложения из представленных...", в массиве, который я посчитал назвать аналогично MESSAGES[], чтобы не путать объект КОММЕНТАРИЙ от ТЕКСТА комментария.

2022-03-02 17:34 UTC, radamid commented on js/util.js
> +  return function () {
Здесь мне нужно исправить строку 11? Так? **function createIdGenerator () {**

2022-03-03 03:47 UTC, bbalkonsky commented on js/util.js
> +  return function () {
нет, возвращаемую сделать стрелочной

2022-03-03 13:50 UTC, merged